[project]
name = "github-profile-kit"
version = "0.1.0"
description = "github-profile-kit"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
authors = [{ name = "Hyperoot", email = "rajesh@hyperoot.dev" }]
dependencies = [
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
    "pre-commit>=4.1.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = ["ruff>=0.9.7"]
